Repository devleo10/Whooshh, pull requests merged in 2025-03, with the labels that each got.

#27 Added temperature unit toggle (°C ↔ °F)
  index.html
  script.js
  style.css
Labels: enhancement, easy, apertre2.0

#26 Added GPS-based location fetching for weather search
  index.html
  script.js
  style.css
Labels: enhancement, easy, apertre2.0

#31 Optimized image fetching
  script.js
  style.css
Labels: bug, enhancement, easy, apertre2.0

#44 Add weekly weather forecast feature
  index.html
  script.js
  style.css
Labels: enhancement, easy, apertre2.0

#41 update readme file
  README.md
Labels: apertre2.0, doc

#13 Fix: Weather icon not displaying properly
  script.js
  style.css
Labels: bug, medium, apertre2.0

#62 Added weather comparison feature
  index.html
  script.js
  style.css
Labels: enhancement, medium, apertre2.0

#67 UI update for Compare
  index.html
  script.js
  style.css
Labels: enhancement, medium, apertre2.0
